### ISSUE TITLE
Add log file rotation

### ISSUE THREAD

**Issue by engram-design** [putyourlightson/craft-log-to-file#1]
I use this a lot on custom modules, and works a treat - thanks!

It'd be great to include log file rotation for when log files get too large, like Craft/Yii does. I recall doing this for Feed Me (https://github.com/craftcms/feed-me/blob/develop/src/services/Logs.php#L142-L228), so will put together a PR at some point if you think its a good idea!

**Comment by putyourlightson** [comment]
Great idea, a PR would be much appreciated Josh!

**Comment by engram-design** [comment]
Still planning on doing this, just haven't had the time to put it together! One of these days 😁

**Comment by engram-design** [comment]
Forgot to tag https://github.com/putyourlightson/craft-log-to-file/pull/3
