### ISSUE TITLE
Ability to pass variables or arrays to log message

### ISSUE THREAD

**Issue by sjelfull** [putyourlightson/craft-log-to-file#2]
I often pass variables to my error messages to add more context, or pass an array to the log to easily debug something.

To ease this, I often add this sugar on top of your sweet log helper:

```php
public static function error($error, $variables = [])
{
    $handle    = static::$plugin->id;
    $variables = self::formatLogVariables($variables);
    $message   = self::formatLogMessage($error, $variables);

    LogToFile::error($message, $handle);
}

public static function info($message, $variables = [])
{
    $handle    = static::$plugin->id;
    $variables = self::formatLogVariables($variables);
    $message   = self::formatLogMessage($message, $variables);

    LogToFile::error($message, $handle);
}

public static function formatLogVariables($variables = [])
{
    $variables = array_map(function($value) {
        if (is_array($value)) {
            $value = Json::encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        }

        return $value;
    }, $variables);

    return $variables;
}

public static function formatLogMessage($message, $variables = [])
{
    $handle = static::$plugin->id;

    if (is_array($message)) {
        $message = Json::encode($message, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    }
    else {
        $message = Craft::t($handle, $message, $variables);
    }

    return $message;
}
```

This way you can do `Plugin::error($array)`, or `Plugin::error('Failed to validate data: {model}', ['model' => $model->toArray()])`.

Makes sense? Want me to PR it?

On a side note, the plugin methods could easily be a trait, which would make it plug-n-play.

**Comment by bencroker** [comment]
I understand your reasoning , however the methods intentionally make as few assumptions as possible about how you want any variables to be parsed. For example, the way I generally use this in a real-world plugin is:
```php
LogToFile::error(Craft::t('my-plugin-handle', $message, $variables), 'my-plugin-handle');
```

But someone else might want to use it as follows:
```php
LogToFile::error($message.': '.implode(', ', $variables)), 'my-plugin-handle');
```

I realise that your implementation would be able to deal with both of the examples above, but I'm not sure if making the assumption that variables should be JSON encoded is wise.

> On a side note, the plugin methods could easily be a trait, which would make it plug-n-play.

While that would make the methods available on the plugin class itself, it is also a bit more involved to override the trait method if someone wanted their own log methods, like it is done in Blitz:
```php
    public function log(string $message, array $params = [], string $type = 'info')
    {
        $message = Craft::t('blitz', $message, $params);

        LogToFile::log($message, 'blitz', $type);
    }
```
https://github.com/putyourlightson/craft-blitz/blob/3.4.1/src/Blitz.php#L127-L139

While I probably could be convinced that a Trait is a more elegant implementation, I'm not sure changing it with a breaking change would bring much in the way of added value.

**Comment by engram-design** [comment]
My 2 cents on this is to keep the API similar to Craft, and using translations to deal with variables in a string. Still, handy resource @sjelfull if we wanted to do something on our own.

**Comment by bencroker** [comment]
Agreed @engram-design, nice to see various approaches.
